services:
  - type: web
    name: namhya-taskmanager-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FOUNDER_EMAIL
        sync: false
      - key: PORT
        value: 5000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: DASHBOARD_URL
        sync: false
